### ISSUE TITLE
Error with calculation of FWHM

### ISSUE THREAD

**Issue by mrakitin** [mrakitin/SRW#36]
```py
mrakitin@cpu-001:~/calc/SMI/tab_und/2017-05-09_Espread_sims$ view_srw res_spec_me_01_emx_0.79369_emy_10.53617_ens_0.7.dat
Traceback (most recent call last):
  File "/home/mrakitin/src/mrakitin/SRW/env/work/srw_python/SRWLIB_ExampleViewDataFile.py", line 38, in <module>
    opt.scale, opt.width_pixels) #MR29072016
  File "/nfs/mrakitin/src/mrakitin/SRW/env/work/srw_python/uti_plot.py", line 170, in uti_data_file_plot
    _scale, _width_pixels) #MR20012017
  File "/nfs/mrakitin/src/mrakitin/SRW/env/work/srw_python/uti_plot_matplotlib.py", line 114, in uti_data_file_plot
    fwhm_dict = uti_math.fwhm(np.linspace(allrange[0], allrange[1], allrange[2]), data, return_as_dict=True)
  File "/nfs/mrakitin/src/mrakitin/SRW/env/work/srw_python/uti_math.py", line 648, in fwhm
    raise Exception('Number of roots is less than 2!')
Exception: Number of roots is less than 2!
```

Need to show the plot anyway.

**Comment by mrakitin** [comment]
Fixed via 67a6d2e and https://github.com/radiasoft/SRW-light/commit/da3a60f8e785a54a42c74abaf3cd33d5e863f491.
